; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "My Program"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{50C7727F-4F93-4D2D-94C1-70459AD87174}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=S:\WORK\Projects\Token Manager\04. Resources\Registry_Test
OutputBaseFilename=setup
SetupIconFile=S:\WORK\Projects\Token Manager\02. Sources\TokenManager\TokenManager\Resources\logovdc_131479250566458834.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 5\Examples\MyProg.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; VNPT-CA-CTDT PKI-Token CSP
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT PKI-Token CSP"; ValueType: string; ValueName: "Image Path"; ValueData: "%SystemRoot%\SysWOW64\vnpt-ca_csp11_s.dll"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT PKI-Token CSP"; ValueType: binary; ValueName: "Signature"; ValueData: "66 1f fe c8 52 45 65 56 8b 3a a1 d7 c4 94 e3 66 c0 21 7c 93 5f 09 2f 8f 2d ae c2 f7 de 27 b5 53 38 21 88 fe 67 42 f2 73 9e a0 2d b1 f8 87 8f 7b 06 67 fd ff f5 d4 2a e9 8d 46 d0 56 ba 49 b6 d0 35 ea 76 6a 17 16 81 b1 2b 42 4a e9 18 09 79 9d 89 7e 3c c4 45 d4 d9 3a db 3f 2e 0a 30 fd c3 30 b2 d3 a2 45 e2 e8 6e df 25 2c bd e6 1a 46 b4 24 0b 68 03 09 dd ae 65 bc 80 d1 84 dc 64 15 50 13 00 00 00 00 00 00 00 00"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT PKI-Token CSP"; ValueType: dword ; ValueName: "Type"; ValueData: 1
; VNPT-CA-CTDT v6-Token CSP
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT V6-Token CSP"; ValueType: string; ValueName: "Image Path"; ValueData: "%SystemRoot%\SysWOW64\vnptca_p11_v6_s.dll"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT V6-Token CSP"; ValueType: binary; ValueName: "Signature"; ValueData: "66 1f fe c8 52 45 65 56 8b 3a a1 d7 c4 94 e3 66 c0 21 7c 93 5f 09 2f 8f 2d ae c2 f7 de 27 b5 53 38 21 88 fe 67 42 f2 73 9e a0 2d b1 f8 87 8f 7b 06 67 fd ff f5 d4 2a e9 8d 46 d0 56 ba 49 b6 d0 35 ea 76 6a 17 16 81 b1 2b 42 4a e9 18 09 79 9d 89 7e 3c c4 45 d4 d9 3a db 3f 2e 0a 30 fd c3 30 b2 d3 a2 45 e2 e8 6e df 25 2c bd e6 1a 46 b4 24 0b 68 03 09 dd ae 65 bc 80 d1 84 dc 64 15 50 13 00 00 00 00 00 00 00 00"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\VNPT-CA-CTDT V6-Token CSP"; ValueType: dword ; ValueName: "Type"; ValueData: 1
; Bkav-CA-CTDT Token CSP
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\Bkav-CA-CTDT Token CSP"; ValueType: string; ValueName: "Image Path"; ValueData: "%SystemRoot%\SysWOW64\BkavCA_s.dll"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\Bkav-CA-CTDT Token CSP"; ValueType: binary; ValueName: "Signature"; ValueData: "66 1f fe c8 52 45 65 56 8b 3a a1 d7 c4 94 e3 66 c0 21 7c 93 5f 09 2f 8f 2d ae c2 f7 de 27 b5 53 38 21 88 fe 67 42 f2 73 9e a0 2d b1 f8 87 8f 7b 06 67 fd ff f5 d4 2a e9 8d 46 d0 56 ba 49 b6 d0 35 ea 76 6a 17 16 81 b1 2b 42 4a e9 18 09 79 9d 89 7e 3c c4 45 d4 d9 3a db 3f 2e 0a 30 fd c3 30 b2 d3 a2 45 e2 e8 6e df 25 2c bd e6 1a 46 b4 24 0b 68 03 09 dd ae 65 bc 80 d1 84 dc 64 15 50 13 00 00 00 00 00 00 00 00"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Cryptography\Defaults\Provider\Bkav-CA-CTDT Token CSP"; ValueType: dword ; ValueName: "Type"; ValueData: 1

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

